server:
  port: 80
spring:
  application:
    name: consul-consumer-order
  cloud:
    consul:
      host: 116.62.138.50
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        prefer-ip-address: true
        heartbeat:
          enabled: true